### ISSUE TITLE
TypeError: 'Dense' object is not iterable

### ISSUE THREAD

**Issue by Gunkkk** [cmu-transparency/lib-attribution#1]
it reports that,

105     inbound_layers = []
    106     for i_node in l._inbound_nodes:
--> 107         for i_layer in i_node.inbound_layers:
    108             inbound_layers.append(i_layer)
    109     return inbound_layers
TypeError: 'Dense' object is not iterable

Thanks!

**Comment by Gunkkk** [comment]
sloved by disable_eager_execution although there are still lots of bugs from version inconsistency, i guess.

**Comment by klasleino** [comment]
This code was originally written for Theano, not TensorFlow, and I'm not sure what versions are required to make it work since I no longer have the environment I used to develop it. However, I wouldn't recommend using this library; it's mainly here for archival purposes. I would instead recommend you check out [trulens](https://github.com/truera/trulens), which we worked with a company called Truera to create. Trulens implements the core of our approach and is [documented](https://truera.github.io/trulens/) and actively maintained.

**Comment by Gunkkk** [comment]
> This code was originally written for Theano, not TensorFlow, and I'm not sure what versions are required to make it work since I no longer have the environment I used to develop it. However, I wouldn't recommend using this library; it's mainly here for archival purposes. I would instead recommend you check out [trulens](https://github.com/truera/trulens), which we worked with a company called Truera to create. Trulens implements the core of our approach and is [documented](https://truera.github.io/trulens/) and actively maintained.

Thank u for your advice.
